Tushar Garade CS23005

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/mldataset/pulsar_stars.csv'
df = pd.read_csv(path)
df.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.columns

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve', ' Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df.isnull().sum()

 Mean of the integrated profile                  0
 Standard deviation of the integrated profile    0
 Excess kurtosis of the integrated profile       0
 Skewness of the integrated profile              0
 Mean of the DM-SNR curve                        0
 Standard deviation of the DM-SNR curve          0
 Excess kurtosis of the DM-SNR curve             0
 Skewness of the DM-SNR curve                    0
target_class                                     0
dtype: int64

In [ ]:
df[df.isnull().any(axis = 1)]

Empty DataFrame
Columns: [ Mean of the integrated profile,  Standard deviation of the integrated profile,  Excess kurtosis of the integrated profile,  Skewness of the integrated profile,  Mean of the DM-SNR curve,  Standard deviation of the DM-SNR curve,  Excess kurtosis of the DM-SNR curve,  Skewness of the DM-SNR curve, target_class]
Index: []

In [ ]:
df.describe()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
count,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000
mean,111.079968,46.549532,0.477857,1.770279,12.614400,26.326515,8.303556,104.857709,0.091574
std,25.652935,6.843189,1.064040,6.167913,29.472897,19.470572,4.506092,106.514540,0.288432
min,5.812500,24.772042,-1.876011,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.929688,42.376018,0.027098,-0.188572,1.923077,14.437332,5.781506,34.960504,0.000000
50%,115.078125,46.947479,0.223240,0.198710,2.801839,18.461316,8.433515,83.064556,0.000000
75%,127.085938,51.023202,0.473325,0.927783,5.464256,28.428104,10.702959,139.309330,0.000000
max,192.617188,98.778911,8.069522,68.101622,223.392141,110.642211,34.539844,1191.000837,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0    Mean of the integrated profile                17898 non-null  float64
 1    Standard deviation of the integrated profile  17898 non-null  float64
 2    Excess kurtosis of the integrated profile     17898 non-null  float64
 3    Skewness of the integrated profile            17898 non-null  float64
 4    Mean of the DM-SNR curve                      17898 non-null  float64
 5    Standard deviation of the DM-SNR curve        17898 non-null  float64
 6    Excess kurtosis of the DM-SNR curve           17898 non-null  float64
 7    Skewness of the DM-SNR curve                  17898 non-null  float64
 8   target_class                                   17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [ ]:
print(df)

        Mean of the integrated profile  \
0                           140.562500
1                           102.507812
2                           103.015625
3                           136.750000
4                            88.726562
...                                ...
17893                       136.429688
17894                       122.554688
17895                       119.335938
17896                       114.507812
17897                        57.062500

        Standard deviation of the integrated profile  \
0                                          55.683782
1                                          58.882430
2                                          39.341649
3                                          57.178449
4                                          40.672225
...                                              ...
17893                                      59.847421
17894                                      49.485605
17895                                      59.935939
17896                                      53.902400
17897                                      85.797340

        Excess kurtosis of the integrated profile  \
0                                       -0.234571
1                                        0.465318
2                                        0.323328
3                                       -0.068415
4                                        0.600866
...                                           ...
17893                                   -0.187846
17894                                    0.127978
17895                                    0.159363
17896                                    0.201161
17897                                    1.406391

        Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                                -0.699648                   3.199833
1                                -0.515088                   1.677258
2                                 1.051164                   3.121237
3                                -0.636238                   3.642977
4                                 1.123492                   1.178930
...                                    ...                        ...
17893                            -0.738123                   1.296823
17894                             0.323061                  16.409699
17895                            -0.743025                  21.430602
17896                            -0.024789                   1.946488
17897                             0.089520                 188.306020

        Standard deviation of the DM-SNR curve  \
0                                    19.110426
1                                    14.860146
2                                    21.744669
3                                    20.959280
4                                    11.468720
...                                        ...
17893                                12.166062
17894                                44.626893
17895                                58.872000
17896                                13.381731
17897                                64.712562

        Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                                  7.975532                      74.242225
1                                 10.576487                     127.393580
2                                  7.735822                      63.171909
3                                  6.896499                      53.593661
4                                 14.269573                     252.567306
...                                     ...                            ...
17893                             15.450260                     285.931022
17894                              2.945244                       8.297092
17895                              2.499517                       4.595173
17896                             10.007967                     134.238910
17897                             -1.597527                       1.429475

       target_class
0                 0
1                 0
2                 0
3                 0
4                 0
...             ...
17893             0
17894             0
17895             0
17896             0
17897             0

[17898 rows x 9 columns]

In [ ]:
x = df.drop(columns=['target_class'])
y = df['target_class']

In [ ]:
x.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
print(x)

       Mean of the integrated profile  \
0                          140.562500
1                          102.507812
2                          103.015625
3                          136.750000
4                           88.726562
...                               ...
17893                      136.429688
17894                      122.554688
17895                      119.335938
17896                      114.507812
17897                       57.062500

       Standard deviation of the integrated profile  \
0                                         55.683782
1                                         58.882430
2                                         39.341649
3                                         57.178449
4                                         40.672225
...                                             ...
17893                                     59.847421
17894                                     49.485605
17895                                     59.935939
17896                                     53.902400
17897                                     85.797340

       Excess kurtosis of the integrated profile  \
0                                      -0.234571
1                                       0.465318
2                                       0.323328
3                                      -0.068415
4                                       0.600866
...                                          ...
17893                                  -0.187846
17894                                   0.127978
17895                                   0.159363
17896                                   0.201161
17897                                   1.406391

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
0                               -0.699648                  3.199833
1                               -0.515088                  1.677258
2                                1.051164                  3.121237
3                               -0.636238                  3.642977
4                                1.123492                  1.178930
...                                   ...                       ...
17893                           -0.738123                  1.296823
17894                            0.323061                 16.409699
17895                           -0.743025                 21.430602
17896                           -0.024789                  1.946488
17897                            0.089520                188.306020

       Standard deviation of the DM-SNR curve  \
0                                   19.110426
1                                   14.860146
2                                   21.744669
3                                   20.959280
4                                   11.468720
...                                       ...
17893                               12.166062
17894                               44.626893
17895                               58.872000
17896                               13.381731
17897                               64.712562

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve
0                                 7.975532                     74.242225
1                                10.576487                    127.393580
2                                 7.735822                     63.171909
3                                 6.896499                     53.593661
4                                14.269573                    252.567306
...                                    ...                           ...
17893                            15.450260                    285.931022
17894                             2.945244                      8.297092
17895                             2.499517                      4.595173
17896                            10.007967                    134.238910
17897                            -1.597527                      1.429475

[17898 rows x 8 columns]

In [ ]:
X = pd.get_dummies(x)

In [ ]:
X.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
X = pd.get_dummies(x,dtype=int)

In [ ]:
X.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
cols = X_train.columns
print(cols)

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve',
       ' Skewness of the DM-SNR curve'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [ ]:
X_train

array([[ 0.43213286,  1.06799569, -0.39846193, ..., -0.06176478,
        -0.14828558, -0.43781826],
       [ 0.41311598, -0.12169419, -0.47762819, ..., -0.69468185,
         1.52768284,  1.36355992],
       [ 0.57219366, -0.16680094, -0.23927494, ..., -0.21160009,
        -0.08080875, -0.34988939],
       ...,
       [ 0.86227648,  1.30236566, -0.54058922, ..., -0.70323001,
         0.86375107,  0.72697842],
       [-0.48973284,  0.3282063 , -0.16276451, ..., -0.52150379,
         0.42561768,  0.17227049],
       [-0.18546282, -0.65481326, -0.06107367, ..., -0.33108755,
        -0.21616313, -0.43256287]])